site_name: CMS Tier 3 at University of Notre Dame

# Navigation bar to be updated upon new pages
nav:
  - Home: index.md
  - Research:
    - Projects: research/projects.md
    - Publications: research/publications.md
  - Resources:
    - Computing: resources/computing.md
    - Data: resources/data.md

theme:
  name: material
  logo: images/nd_logo.png
  favicon: images/nd_logo.png  # Optional: if you want to use the same logo as favicon
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: green
      accent: indigo

# Added to be able to have a "last update at" footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amaltaro/ndcms-docs
  generator: false  # Removes "Made with Material for MkDocs" from footer

# Enable git revision date from git history
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: date

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes